//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RACQAZ.Channel.CMO.NominationMgmt.v1.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RACQAZ.Channel.CMO.NominationMgmt.v1.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cpq_AssetLineItem.AssetNumber,
        ///cpq_AssetLineItem.AssetStatus,
        ///cpq_AssetLineItem.CancellationComments,
        ///cpq_AssetLineItem.CancelledDate,
        ///cpq_AssetLineItem.Description,
        ///cpq_AssetLineItem.StartDate,
        ///cpq_AssetLineItem.EndDate,
        ///cpq_AssetLineItem.ext_PRN,
        ///cpq_AssetLineItem.ext_MembershipTC,
        ///cpq_AssetLineItem.ProductId.ProductCode,
        ///cpq_AssetLineItem.ext_CTPcertificatenumber,
        ///cpq_AssetLineItem.ext_AssetStatus,
        ///cpq_AssetLineItem.Id,
        ///cpq_AssetLineItem.Name,
        ///cpq_AssetLineItem.AccountId,
        ///cpq_AssetAttribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP status code of the response was not expected..
        /// </summary>
        internal static string HttpErrorMessage {
            get {
                return ResourceManager.GetString("HttpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout error occurred.
        /// </summary>
        internal static string HttpTimeoutErrorMessage {
            get {
                return ResourceManager.GetString("HttpTimeoutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        internal static string HttpUnavaliableErrorMessage {
            get {
                return ResourceManager.GetString("HttpUnavaliableErrorMessage", resourceCulture);
            }
        }
    }
}
