// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "xUnit1026:Theory method 'Map_WhenExtVehicleStatusIsNullEmpty_VehicleShouldBeNull' on test class 'AqlResponseToResponseTypeProfileTests' does not use parameter 'value'.", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.Mappers.Responses.AqlResponseToResponseTypeProfileTests.Map_WhenExtVehicleStatusIsNullEmpty_VehicleShouldBeNull(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "xUnit1026:Theory method 'Map_WhenStatusIsNullEmpty_VehicleCoverableListVehicleShouldBeNull' on test class 'AqlResponseToResponseTypeProfileTests' does not use parameter 'value'.", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.Mappers.Responses.AqlResponseToResponseTypeProfileTests.Map_WhenStatusIsNullEmpty_VehicleCoverableListVehicleShouldBeNull(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.Commands.UpdateAgreementsCommandsTests.CannotConstructWithNullAssetLineItemMapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.Commands.UpdateAgreementsCommandsTests.CannotConstructWithNullVehicleTypeMapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.Commands.UpdateAgreementsCommandsTests.CannotConstructWithNullAssetAttributeMapper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.Commands.UpdateAgreementsCommandsTests.CannotConstructWithNullApttusService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.Commands.UpdateAgreementsCommandsTests.CannotCallExecuteAsyncWithNullRequest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:RACQAZWEBAPI.Product.ProductAgreementMgmt.v1.UnitTests.ViewModels.Responses.ProductAgreementExtensionsTests.CannotCallContainsAssetLineItemIdWithNullProductAgreement")]
